### PR TITLE
Olwa pr

### PR DESCRIPTION
**Pull request by oliver-walker-hms**

### CODE REVIEW

**Review by TomKimsey — COMMENTED** [review]
Why not just wait till you rename the repo for this. If you want me to rename it I can.

**Comment by oliver-walker-hms** [comment]
this is a new pr from when you looked at it that has the name change taken into account. I would of remade it but it's a small change

**Review by TomKimsey — CHANGES_REQUESTED** [review]
Your build is failing, i would expect to see some classpath changes associated with the library rename.

**Comment by alexjhawk** [comment]
@oliver-walker-hms You'll need to remove it entirely from the file system and delete the entry in .gitmodules and you will need to check it out again with 'git submodule add -b release/1.2 https://github.com/hms-networks/....'

**Comment by alexjhawk** [comment]
> @oliver-walker-hms You'll need to remove it entirely from the file system and delete the entry in .gitmodules and you will need to check it out again with 'git submodule add -b release/1.2 https://github.com/hms-networks/....' -- it didn't work for me to just directly rename and edit

Also, you'll need to edit the folder name in https://github.com/hms-networks/flexy-osisoft-connector/blob/master/.github/workflows/ewon-java-build-ant.yml

Since the libraries are not in a subfolder like lib/, the script has the folder name hardcoded

**Comment by oliver-walker-hms** [comment]
Thanks @alexjhawk , that saved me some time. can you guys do the other pr first and I'll rebase this one after that

**Review by alexjhawk — APPROVED** [review]

**Review by TomKimsey — APPROVED** [review]

**Comment by TomKimsey** [comment]
@oliver-walker-hms what is the status of this PR?

**Pull request merged**
